import { relations } from "drizzle-orm";
import {
  boolean,
  date,
  index,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid
} from "drizzle-orm/pg-core";
import { households } from "./households";
import { users } from "./auth";

export const effortLevelEnum = pgEnum("effort_level", [
  "quick",
  "easy",
  "medium",
  "high_effort"
]);

export const meals = pgTable(
  "meals",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    // Round 4 households: meals scope to a household, not a single user.
    // TS shape reflects the POST-0016 schema. If this code is deployed
    // before all three round-4 migrations have run, inserts will reject
    // (the live DB still has user_id NOT NULL with no default).
    // APPLY 0014 + 0015 + 0016 BEFORE DEPLOYING this code.
    householdId: uuid("household_id")
      .notNull()
      .references(() => households.id, { onDelete: "cascade" }),
    // Attribution: who first added this recipe to the household. Set on
    // insert only; never overwritten when other members cook the meal.
    // ON DELETE SET NULL so removing a member doesn't cascade-delete
    // recipes other members still want. POST-0018: nullable in DB too —
    // 0016 had tightened it to NOT NULL which contradicted the SET NULL
    // FK and silently broke account deletion. UI renders "Former member"
    // via lib/meals/attribution.ts when this is null.
    createdByUserId: text("created_by_user_id").references(() => users.id, {
      onDelete: "set null"
    }),
    name: text("name").notNull(),
    normalizedName: text("normalized_name").notNull(),
    photoUrl: text("photo_url"),
    notes: text("notes"),
    recipeText: text("recipe_text"),
    recipeSourceUrl: text("recipe_source_url"),
    // Free-form yield/servings, e.g. "Serves 4", "Makes 8 sliders",
    // "Feeds 6". Intentionally a string (not a number) so it can carry
    // the unit naturally. AI-filled on capture/refine; editable via Refine.
    servings: text("servings"),
    // Round 10: structured ingredient list. Each element is one
    // ingredient line as the AI extracted it ("1 cup basmati rice") —
    // free-text, intentionally not parsed into {name, quantity, unit}.
    // Pantry-state matching is a separate, much larger feature.
    ingredients: text("ingredients").array(),
    // True when the recipe was GENERATED by AI from just a dish name (not read
    // off the user's source), so the recipe view can flag it "review this".
    // Cleared once the user edits it by hand or refines it.
    recipeIsAiDraft: boolean("recipe_is_ai_draft").notNull().default(false),
    // R34 — recipe-level effort override set from the Edit screen. NULL means
    // "derive from the cook logs' modal effort" (the original behaviour, kept
    // for legacy meals + meals never edited). When set, getMealDetail prefers
    // it so a hand-set effort sticks regardless of how it was last cooked.
    effortLevel: effortLevelEnum("effort_level"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    // R36 — user-facing "Archive" (reversible; the recipe is tucked into the
    // Archived view but still openable + restorable). This is what the legacy
    // soft-delete column now means at the product level.
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    // R36 — destructive "Delete" (soft, so Undo can restore the row + its logs
    // and structured rows within the toast window; a purge job is out of scope).
    // Excluded from EVERY view, including the Archived view. Reads that already
    // drop archived rows also drop deleted rows; `getMealDetail` allows archived
    // (Open from Archived) but never deleted.
    deletedAt: timestamp("deleted_at", { withTimezone: true })
    // Sharing is fully per-item now (see db/schema/sharing.ts `item_grants`).
    // The legacy `shared_at` flag + its visibility clause were removed; the
    // canonical predicate in `apps/web/lib/meals/visibility.ts` is
    // own-or-granted.
  },
  (table) => ({
    // Round 4: unique scope moved to (householdId, normalizedName). Two
    // members in the same household can't add the same recipe twice;
    // two households can both have "Soy ginger noodles" with no conflict.
    householdMealIdx: uniqueIndex("meals_household_normalized_name_idx").on(
      table.householdId,
      table.normalizedName
    ),
    householdUpdatedAtIdx: index("meals_household_updated_at_idx").on(
      table.householdId,
      table.updatedAt
    ),
    householdArchivedAtIdx: index("meals_household_archived_at_idx").on(
      table.householdId,
      table.archivedAt
    ),
    householdDeletedAtIdx: index("meals_household_deleted_at_idx").on(
      table.householdId,
      table.deletedAt
    )
  })
);

export const mealLogs = pgTable(
  "meal_logs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    mealId: uuid("meal_id")
      .notNull()
      .references(() => meals.id, { onDelete: "cascade" }),
    // Round 4 households: logs scope to a household + carry attribution
    // for who actually cooked the meal. cookedByUserId is renamed from
    // user_id in migration 0014 (preserves existing data + indexes).
    // POST-0016 state: NOT NULL.
    householdId: uuid("household_id")
      .notNull()
      .references(() => households.id, { onDelete: "cascade" }),
    // POST-0017 state: nullable + ON DELETE SET NULL. The original CASCADE
    // silently wiped a former member's logs across every household they ever
    // joined when they deleted their account. SET NULL preserves the log
    // (history stays in the household) but nulls the attribution — UI
    // renders "Former member" in that case. APPLY 0017 BEFORE deploying
    // this schema.
    cookedByUserId: text("cooked_by_user_id").references(() => users.id, {
      onDelete: "set null"
    }),
    effortLevel: effortLevelEnum("effort_level").notNull(),
    notes: text("notes"),
    cookedAt: date("cooked_at").notNull(),
    photoUrl: text("photo_url"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp("deleted_at", { withTimezone: true })
  },
  (table) => ({
    // Index names retain the pre-rename "user" stem — Postgres index names
    // are independent of column references, so renaming is hygiene-only
    // and intentionally deferred.
    userCookedAtIdx: index("meal_logs_user_cooked_at_idx").on(
      table.cookedByUserId,
      table.cookedAt
    ),
    userMealCookedAtIdx: index("meal_logs_user_meal_cooked_at_idx").on(
      table.cookedByUserId,
      table.mealId,
      table.cookedAt
    ),
    userEffortIdx: index("meal_logs_user_effort_idx").on(
      table.cookedByUserId,
      table.effortLevel
    ),
    mealCookedAtIdx: index("meal_logs_meal_cooked_at_idx").on(
      table.mealId,
      table.cookedAt
    )
  })
);

export const mealRelations = relations(meals, ({ many, one }) => ({
  creator: one(users, {
    fields: [meals.createdByUserId],
    references: [users.id]
  }),
  household: one(households, {
    fields: [meals.householdId],
    references: [households.id]
  }),
  logs: many(mealLogs)
}));

export const mealLogRelations = relations(mealLogs, ({ one }) => ({
  meal: one(meals, {
    fields: [mealLogs.mealId],
    references: [meals.id]
  }),
  cookedBy: one(users, {
    fields: [mealLogs.cookedByUserId],
    references: [users.id]
  }),
  household: one(households, {
    fields: [mealLogs.householdId],
    references: [households.id]
  })
}));
